### ISSUE TITLE
Registration API health resource - spec not matching BBC implementation

### ISSUE THREAD

**Issue by Streampunk** [AMWA-TV/nmos-discovery-registration#1]
The health resource POST is specified as follows:

    /health/nodes/{nodeId}:
      displayName: Node health
      post:
        description: Update Node health
        responses:
          200:
            body:
              example: !include ../examples/registrationapi-v1.0-health-post-200.json
          404:
            description: Returned when the requested Node does not exist or has been garbage collected`

However, the VM provided on box to incubator members behaves differently, responding with a 204 No Content with no body. I think the RAML specification should be:

    /health/nodes/{nodeId}:
      displayName: Node health
      post:
        description: Update Node health
        body:
          example: !include ../examples/registrationapi-v1.0-health-post-200.json
        responses:
          204:
            description: No content successful response.
          404:
            description: Returned when the requested Node does not exist or has been garbage collected`

This was discovered during a side-by-side comparison of ledger's registration service with the bbcrd VM (`bbcrd_ipstudio_exportable_headless_discovery_amd64_master_2016-02-06.ova`).

**Comment by andrewbonney** [comment]
I'd suggest that as things stand this is actually an error in the provided implementation. The intention is that the server side provides the health timestamping rather than the client given there's a chance their clocks might not be in sync with each other. As a result the POST should be performed with an empty payload, with the 200 response to that giving the same response payload as the corresponding GET request.

I have a patch for the issue in the implementation which I'll provide via usual incubator channels shortly.
