### ISSUE TITLE
Example Inaccuracies

### ISSUE THREAD

**Issue by mjeras** [AMWA-TV/nmos-discovery-registration#129]
I have noticed two issues while writing some unit tests using the examples provided in this repository:
- nodeapi-flows-get-200.json - The IS-07 flows (as opposed to the other flows in the array) have "caps" fields, although they are not defined for flows. That seems to originate from the IS-07 documentation samples and has to be corrected there too. The fix is to remove the fields.
- registrationapi-resource-*.json (3 files affected) - The examples show the update for a node, but the node in the example doesn't have "interfaces" property which is mandatory for a node. The fix is to (at least) add an empty "interfaces" array.
I have the fixes for the above locally, but don't have the rights to push them and create a pull request.

**Comment by garethsb** [comment]
👍 Sounds about right. I also feel the example files haven't had as much scrutiny as the schemas and other parts of the specs.

(E.g. [registrationapi-resource-get-200.json](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/examples/registrationapi-resource-get-200.json) basically not been updated since v1.1 spec, hence no `"interfaces"`.)

You should be able to fork this repo, and make a branch based on v1.3.x, and push your changes on that. Then you should be able to submit a PR.

Spec authors can usually then rebase on to v1.2.x, etc. if appropriate.

**Comment by garethsb** [comment]
Closed by #156.
