### ISSUE TITLE
HTTP 500 Error Code

### ISSUE THREAD

**Issue by ghost** [AMWA-TV/nmos-discovery-registration#169]
Hi

Referring to this [page](https://specs.amwa.tv/is-04/releases/v1.3.1/docs/4.1._Behaviour_-_Registration.html).

Can a Node encounter the HTTP 500 error on both Registration and Heartbeats or only on Heartbeats?

If a Node can encounter the code on both, should the same logic apply to both Heartbeats and Registration?

Thanks in advance.

Victor.

**Comment by garethsb** [comment]
A Node needs to be able to handle `500` and other `5xx` errors, and connection timeouts, etc. on both of those endpoints.

**Comment by ghost** [comment]
Ok, then, it would be great to add "On Registration Or Heartbeat" as the other titles have.

**Comment by garethsb** [comment]
What made you think it only applied to a particular endpoint, not to the whole the API?

**Comment by VentuzVictor** [comment]
Hi

I have been working with the NMOS specifications implementation for a couple of months, normally the documentation is very well explained.

In this particular case, the [error conditions](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/docs/4.1.%20Behaviour%20-%20Registration.md#error-conditions) are very specific as to which endpoint has to use certain logic:

- Node Encounters HTTP 200 On First Registration
- Node Encounters HTTP 400 (Or Other Undocumented 4xx) On Registration
- Node Encounters HTTP 409 On Registration Or Heartbeat
- Node Encounters HTTP 404 On Heartbeat

But the last error condition:

-  Node Encounters HTTP 500 (or other 5xx), Inability To Connect, Or A Timeout

misses on which endpoint the explained logic should be applied.

Once you read the according logic you realized that it refers to the heartbeat endpoint, but never mentioned something about the registration endpoint, that's why I preferred to ask, now is clear to me, but maybe for other future readers it won't.

Regards.

Victor.

**Comment by ghost** [comment]
Hi

I have been working with the NMOS specifications implementation for a couple of months, normally the documentation is very well explained.

In this particular case, the error conditions are very specific as to which endpoint has to use certain logic:

    Node Encounters HTTP 200 On First Registration
    Node Encounters HTTP 400 (Or Other Undocumented 4xx) On Registration
    Node Encounters HTTP 409 On Registration Or Heartbeat
    Node Encounters HTTP 404 On Heartbeat

But the last error condition:

    Node Encounters HTTP 500 (or other 5xx), Inability To Connect, Or A Timeout

misses on which endpoint the explained logic should be applied.

Once you read the according logic you realized that it refers to the heartbeat endpoint, but never mentioned something about the registration endpoint, that's why I preferred to ask, now is clear to me.

Regards.

Victor.

**Comment by garethsb** [comment]
Thanks for the feedback. In general, API clients need to gracefully handle `4xx` and `5xx` and connection errors, even when those are not documented in the API (RAML) spec for a particular endpoint (see https://specs.amwa.tv/is-04/releases/v1.3.1/docs/2.0._APIs.html#error-codes--responses). For the Node, as client of the Registration API, the extra guidance is provided to make sure that the fail-over process is followed when there are multiple Registration APIs available. The `5xx` handling therefore applies to the whole API. The open source sony/nmos-cpp documentation has a diagram explaining the state machine:  https://github.com/sony/nmos-cpp/blob/master/Documents/images/node-behaviour.png

**Comment by ghost** [comment]
Cool, thanks for the explanation and the links provided!

**Comment by peterbrightwell** [comment]
Is any further action needed here or can this be closed?
