### ISSUE TITLE
Improve documentation for when a node re-registers with a Registration API

### ISSUE THREAD

**Issue by cmannett85** [AMWA-TV/nmos-discovery-registration#25]
In [Node Encounters HTTP 500 (or other 5xx), Inability To Connect, Or A Timeout On Heartbeat](https://github.com/AMWA-TV/nmos-discovery-registration/blob/master/docs/4.1.%20Behaviour%20-%20Registration.md#node-encounters-http-500-or-other-5xx-inability-to-connect-or-a-timeout-on-heartbeat), it states (emphasis mine):

> As this issue may affect just one Registration API in a cluster, it is recommended that clients identify another Registration API to use from their discovered list. _The first interaction with a new Registration API in this case should be a heartbeat_ to confirm whether the Node is still present in the registry.

What should I do with the result?  Presumably if it's a 404 I'll have to do a full re-register.  But what if it's a 200?  For the first registration we have to do this:

> If a Node receives a 200 code in this case, a previous record of the Node can be assumed to still exist within the network registry. In order to avoid the registry-held representation of the Node's resources from being out of sync with the Node's view, an HTTP DELETE should be performed in this situation to explicitly clear the registry of the Node and any sub-resources.

Surely the same reasoning applies to all initial connections to a Registration API?

**Comment by andrewbonney** [comment]
Yes, if it's a 404 you definitely need to fully re-register. If you receive a 200 rather than a 201 then the registry already has records of your Node.

If you have received a good (200/201) response for every resource registration up until this point and the only error you saw related to a heartbeat against a previous Registration API, the 200 from a new Registration API indicates that everything is fine and you can continue without any re-registrations.

The documentation referring to a 200 on first registration (https://github.com/AMWA-TV/nmos-discovery-registration/blob/master/docs/4.1.%20Behaviour%20-%20Registration.md#node-encounters-http-200-on-first-registration) is talking more about when a Node first comes online rather than the first time you encounter each Registration API in a system.

**Comment by cmannett85** [comment]
Thank you, that's cleared things up.
