### ISSUE TITLE
Use of EmptySchema in GET/DELETE request specification is incorrect

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-discovery-registration#36]
Noted by Gareth Sylvester-Bradley:

The 'EmptySchema' used in the APIs is intended to indicate that the request body can be empty, but in reality if you run it through a validator it requires an empty object to be present '{}'.

This should be replaced with one of the following in the RAML to fix this. It doesn't appear to be possible to fix this correctly using JSON schema directly:

1) Currently preferred: Body parameter removed for requests with no request payload
```
get:
  description: List of paths available from this API
  responses:
    200:
```

2) Body set explicitly to null. Note that when rendered as HTML this indicates that the request body must still have a content type of application/json which isn't mandatory without a request body present.
```
get:
  description: List of paths available from this API
  body: null
  responses:
    200:
```

3) Similar to 2, but using !! to avoid 'null' being interpreted as a literal. This usage isn't 100% clear from the RAML 0.8 spec, but does still appear to validate.
```
get:
  description: List of paths available from this API
  body: !!null
  responses:
    200:
```

**Comment by garethsb** [comment]
Also heartbeat POST?

**Comment by andrewbonney** [comment]
Yes indeed. It affects everywhere that the EmptySchema is used at present.

**Comment by sparkpunkd** [comment]
I think the issue is resolved well by the proposed pull request.

Pedant mode on again! For the heartbeat POST, is any kind of body allowed? What should the `Content-Type` header be ... if it is `application/json` and I post content of length zero, is this invalid JSON (i.e. not `{}` or `[]`)? Perhaps something in the docs to say the POST should have an empty message indicated by `Content-Length: 0` and maybe no `Content-Type`? 

(Sorry if I missed that somewhere?)

Richard

**Comment by andrewbonney** [comment]
I believe the `Content-Type` header can be omitted where there is no message body, and as you suggest this may well be the best option in this case to avoid getting into CORS issues with GET requests. Having said that I wouldn't necessarily want a server implementation to reject a message because it happens to have a payload, for example signalled as type `text/html` as it shouldn't be interpreted. Perhaps this ought to be added along the lines of 'API clients SHOULD send an empty body with no Content-Type specified for any API methods which don't specify a request body', with nothing specified on the server side?

On `Content-Length` I'd note that I've certainly observed client libraries in the past which fail to set this value, so I wouldn't necessarily want to mandate it and force people not to use certain HTTP client libraries.

**Comment by sparkpunkd** [comment]
Thanks. I like that approach to `Content-Type`. I assume this is an extra section in [section 2.2](https://github.com/AMWA-TV/nmos-discovery-registration/blob/master/docs/2.2.%20APIs%20-%20Client%20Side%20Implementation%20Notes.md) of the docs?

Treating `Content-Length: 0` and no content length header present seems to be accepted practice or arguably even expected behaviour, e.g.:

http://lists.w3.org/Archives/Public/ietf-http-wg/2010JulSep/0275.html

Therefore, I would agree that no further documentation in NMOS is required for this aspect.

**Comment by andrewbonney** [comment]
Yes I think that makes sense. I'll add a note into 2.2 as part of the same PR.
