### ISSUE TITLE
"symbol" not required in schema "source_audio.json"

### ISSUE THREAD

**Issue by thosil** [AMWA-TV/nmos-discovery-registration#62]
Hello,

I don't get the point where an audio channel is described with only a free text label (which could be "").
So, shouldn't the property "symbol" be required?

**Comment by andrewbonney** [comment]
Hi Thomas,
Yes, in an ideal case the 'symbol' would be a required parameter. The reason it has been specified as optional here relates to the level of configuration which certain classes of device may require in order to fill it in accurately.

An SDI/IP gateway for example may not know which symbol should be applied to each of the 16 channels it may be handling. If this parameter was required, the concern is that the initial (out of the box) configuration of such a device would be based upon a guess (for example a repeating L,R,L,R pattern). Having incorrect metadata associated with the audio appears to be a worse behaviour than having the metadata missing until it has been configured correctly.
