### ISSUE TITLE
Query Parameters link not working in QueryAPI.html - v1.2_spec

### ISSUE THREAD

**Issue by cristian-recoseanu** [AMWA-TV/nmos-discovery-registration#65]
Link:

[https://amwa-tv.github.io/nmos-discovery-registration/tags/v1.2_spec/html-APIs/QueryAPI.html](https://amwa-tv.github.io/nmos-discovery-registration/tags/v1.2_spec/html-APIs/QueryAPI.html)

This section here I think is where the problem is:

For a full description of the expected querying behaviour along with examples, please see the [Query Parameters Documentation](../docs/2.5. APIs - Query Parameters.md).

**Comment by andrewbonney** [comment]
That's a challenge. The link (once it's rendered as HTML) should be '../docs/2.5._APIs_-_Query_Parameters.html', so all spaces change to underscores and the .md extension changes to .html. We'll see if there's anything we can do to sort this out as part of the rendering process @peterbrightwell 

The same goes for any other links from the rendered RAML to documentation pages.

**Comment by peterbrightwell** [comment]
I've added an extra part to fix-links.sh to do this.  The link above is no longer valid following release renaming, but e.g. this should now be ok:

https://amwa-tv.github.io/nmos-discovery-registration/tags/v1.2/html-APIs/QueryAPI.html

This is all rather messy, due to the mixed approach to generating the documentation trees (partly in scripts, partly back-end in Jekyll).  We may want to look at a new approach longer term.

@cristian-recoseanu can you confirm this is ok?

**Comment by andrewbonney** [comment]
I'm confident this is sorted so will close the issue, but feel free to re-open if any other cases are identified.
