### ISSUE TITLE
Expand defined set of Receiver capabilities

### ISSUE THREAD

**Issue by andrewbonney** [AMWA-TV/nmos-discovery-registration#89]
At present Receiver capabilities are defined to differentiate between the different media_types which Flows may use. In order for control systems to make informed routing decisions these need to cover a greater spectrum of Source/Flow attributes. Some initial prototyping in this area has been carried out in https://github.com/bbc/nmos-discovery-registration/pull/6, but is incomplete.

**Comment by andrewbonney** [comment]
Suggest for the purposes of v1.3 and to avoid delaying it unnecessarily, it is noted that any new capabilities are expected to be defined externally and independent of the IS-04 version. This at least leaves the possibility open, with a provisional intent to document these in the parameter registers in a similar style to the mini schema format discussed in https://github.com/bbc/nmos-discovery-registration/pull/6. As part of this 'caps' keys could be made to exactly match any valid Source or Flow attribute name.

**Comment by andrewbonney** [comment]
Subject to #112 being merged this issue can be dealt with outside of the core specification.

**Comment by garethsb** [comment]
User stories for Receiver caps:
* An audio Receiver can only accept 8/16/64 channels (enumerated list) (#147)
* A video Receiver can be configured outside NMOS, so at any time it either accepts 4K or HD, never both
* A video Receiver can accept a limited range of frame rates (enumerated list)
* A video Receiver can accept any frame rate up to a maximum (min/max constraint?)
* A video Receiver can accept HD at up to 60 frames per second but 4K only up to 25fps, e.g. due to link limit (combination)

**Comment by garethsb** [comment]
Possible approaches to defining different kinds of single-attribute capability in a common way:

1. Naming capabilities that correspond to Source/Flow/Sender attributes
   * Use the attribute name directly (e.g. `"frame_width"`) or pluralized (`"frame_widths"`) like existing `"media_types"` capability, either of which may enable a Controller to make a generic look-up in Source/Flow/Sender (though not indicate which...)
     If pluralized, what about already plural Source/Flow/Sender names like `"components"` and `"channels"`?
   * Or allow free naming (meeting `snake_case` convention) and have to define the associated Source/Flow/Sender attribute(s) and potentially semantics externally?
      (E.g. like `"min_frame_width"` in the https://github.com/bbc/nmos-discovery-registration/pull/6 strawman proposal.)

2. Expressing capabilities that correspond to single Source/Flow/Sender attributes
   Consider basing individual attribute capability on IS-05 constraints schema, i.e. an object with properties:
   * `"enum"` (array of valid json values, allowing object and array as well as scalar types to handle e.g. `"grain_rate"` and `"components"`)
   * `"minimum"` and/or `"maximum"` - may be good alternatives to `"enum"` for `"frame_width"`, `"bit_depth"`, etc.
   * `"pattern"`: for string attributes, if required
   Open issues:
   * optionally allow array value capability as shorthand for object capability with `"enum"` (i.e. as used for existing `"media_types"` and `"event_types"`)
   * how should the capability of "less than 16 audio channels" or "exactly 8, 16 or 64 channels" be expressed?
     (`"channels"` is an array of objects in an audio Source; adding the `"minItems"` and `"maxItems"` constraints would help with the former use case but not the latter unless used in `"anyOf"`... adding `"numItems": [ 8, 16, 64 ]` would seem reasonable?)
   * how could the capability of "any grain rate up to 120Hz" be expressed? (`"minimum"` doesn't work if it can only accept `number` not a grain rate rational... so maybe we specifically have to add support for `"mini/maximum"` with rational?)
   * many attributes are single scalar values, some are 'simple' objects (like the rational values); are there attributes that may need constraints on specific properties of sub-objects, like `"DID_SDID"`, `"channels"` and `"components"` or is enumerating the entire array value (ordered or unordered, hmm) acceptable here?

Possible approaches to representing valid combinations of single-attribute capabilities:
* `"anyOf"` and `"allOf"` caps, which take JSON array of caps objects
  * top-level `anyOf` allows simple enumerated lists
  * `allOf` used with `anyOf` recursively allows Boolean AND-OR expressions
* `"tags"` capabilities, e.g. `"tags": { "urn:x-manufacturer:video-op": [ "1080p24", "1080p25", "1080p29.97", ... ], ... }`
  * big downside - completely independent definition from single-attribute caps
  * would benefit from regex pattern constraints mentioned above

**Comment by garethsb** [comment]
Listing up the attributes that are available to controllers...

Some basics are already covered by Receiver properties or existing `caps`. The Sender `transport` is matched against Receiver `transport`. Source/Flow `format` attributes are matched against Receiver `format`. The Flow `media_type` attributes are covered by Receiver `caps.media_types`, as `event_types` from source_data/flow_data is by Receiver `caps.event_types`.

The remaining useful attributes are almost all in the Flows:

* flow_core
  * `grain_rate` - object (`numerator` and `denominator`)
* flow_audio
  * `sample_rate` - object (`numerator` and `denominator`)
* flow_audio_raw
  * `bit_depth` - integer
* flow_sdianc_data
  * `DID_SDID` - array of object (with `DID` and `SDID` - both strings)
* flow_video
  * `frame_width` - integer
  * `frame_height` - integer
  * `interlace_mode` - string (enum)
  * `colorspace` - string (enum)
  * `transfer_characteristic` - string (enum)
* flow_video_raw
  * `components` - array of object (with `name` - string (enum), `width`, `height`, `bit_depth` - all integers)

There's one useful Source attribute:

* source_audio
  * `channels` - array of object (with `label` - string and `symbol` - string (enum))

As mentioned above resource_core `tags` is another possibility for matching.

However, since there is a proposal to allow Source/Flow attributes to be extended via NMOS Parameter Registers (https://github.com/AMWA-TV/nmos-parameter-registers/pull/13), we shouldn't focus _too_ tightly on the existing set of attributes.

**Comment by garethsb** [comment]
Resolved by [BCP-004-01](https://specs.amwa.tv/bcp-004-01)! :-)
