### ISSUE TITLE
Peer-to-peer deprecated

### ISSUE THREAD

**Issue by bgilmer77** [AMWA-TV/nmos-discovery-registration#94]
Suggest adding a note that peer-to-peer mode is deprecated.

**Comment by kaywang26** [comment]
Is peer-to-peer mode deprecated? where did you know that?

**Comment by kaywang26** [comment]
I found it: https://github.com/AMWA-TV/nmos/wiki/IS-04

**Comment by garethsb** [comment]
That link indicates that peer-to-peer mode will become *optional* - and "not recommended in systems which include more than a few tens of Nodes". That is quite different than *deprecated*.

Recent posts on Basecamp have indicated there are use cases for ad-hoc deployments rather than engineered facilities. If peer-to-peer operation were deprecated, such deployments would require a Registry. Is that the intention?

**Comment by andrewbonney** [comment]
I did clarify this with @bgilmer77 when the issue was posted. The request was for a note around the upcoming v1.3 changes in the earlier versions so that readers know they are imminent. I believe from that discussion and those on Basecamp that the draft text in v1.3 making the Node's announcement optional but not deprecated is still correct.

**Comment by bgilmer77** [comment]
My original comment was in error, and @garethsb-sony has accurately captured what I was trying to say.  Peer-to-peer mode should be _optional_ and "not recommended in installations which include more than a few tens of Nodes."  Well said.

**Comment by peterbrightwell** [comment]
Notes added.
